[project]
name = "lidr-ai-engineering-202609"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[dependency-groups]
dev = [
    "ruff>=0.16.7",
]

[tool.ruff.lint]
select = ["E", "W", "F", "I"]

